export const communalItems = [
  { name: 'apples' },
  { name: 'bananas' },
  { name: 'oranges' },
  { name: 'clementines' },
]

export const garrettItems = [
  { name: 'tuna salad', increment: 6 },
  { name: 'bread', increment: 8 },
  { name: 'cheese', increment: 20 },
  { name: 'lettuce', increment: 16 },
  { name: 'mayonnaise', decrement: 0.1 },
  { name: 'tuna cans', increment: 2 },
  { name: 'chopped veggies', increment: 12 },
  { name: 'relish (backup)', increment: 6 },
  { name: 'soylent Mocha drink' },
  { name: 'soylent Mint Choc drink' },
  { name: 'soylent Mocha powder', decrement: 0.1 },
  { name: 'soy milk', decrement: 0.1 },
  { name: 'chocolate syrup', decrement: 0.1 },
  { name: 'cereal', decrement: 0.1 },
  { name: 'coke (big)' },
  { name: 'coke (small)' },
  { name: 'coke Zero (small)' },
  { name: 'steamable meals' },
  { name: 'noodle bowls' },
  { name: 'protein bars' },
  { name: 'chip bags' },
  { name: 'dairy milk', decrement: 0.1 },
  { name: 'peanut butter', decrement: 0.1 },
]
